---
name: Continuous Integration - PR

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

env:
  COMMIT_RANGE: ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}

jobs:

  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: composer, cs2pr
      - id: cache-php-cs-fixer-vendor
        uses: actions/cache@v3
        with:
          path: |
            tools/php-cs-fixer/vendor
          key: php-cs-fixer-vendor-${{ hashFiles('tools/php-cs-fixer/composer.lock') }}
      - if: steps.cache-php-cs-fixer-vendor.outputs.cache-hit != 'true'
        run: composer --working-dir=tools/php-cs-fixer install
      - uses: actions/cache@v3
        with:
          path: .php-cs-fixer.cache
          key: php-cs-fixer-cache-${{ hashFiles('tools/php-cs-fixer/composer.*', '.php-cs-fixer.dist.php') }}
      - run: >
          tools/php-cs-fixer/vendor/bin/php-cs-fixer fix
          --config=.php-cs-fixer.dist.php
          --diff
          --dry-run
          --format=checkstyle
          --path-mode=intersection
          --
          $(git diff --name-only --diff-filter=ACMRTUXB "${COMMIT_RANGE}")
          | cs2pr --colorize --prepend-filename --prepend-source

  phpstan:
    runs-on: ubuntu-latest
    name: phpstan
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: cs2pr, phpstan
      - run: phpstan --error-format=checkstyle | cs2pr

  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.0, 7.4]
        stability: [prefer-lowest, prefer-stable]
    name: phpunit on PHP ${{ matrix.php }}@${{ matrix.stability }}
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          coverage: xdebug
      - run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction # yamllint disable-line
      - run: vendor/bin/phpunit

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ibiqlik/action-yamllint@v3
        with:
          format: github
          config_data: |
            extends: default
            rules:
              truthy:
                check-keys: false
